services:
  sing-box:
    image: ${SING_BOX_IMAGE}
    container_name: sing-box
    command: run -c /etc/sing-box/config.json
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ${SING_BOX_CONFIG_DIR}:/etc/sing-box
      - ${SUB_STORE_DATA_DIR}:/etc/sub-store:ro
    environment:
      - TZ=Asia/Shanghai

  sub-store:
    build:
      context: .
      dockerfile: Dockerfile.sub-store
      args:
        BASE_IMAGE: ${SUB_STORE_BASE_IMAGE}
        SUB_STORE_PUBLIC_API: http://${MY_IP}:9002
    image: ${SUB_STORE_IMAGE}
    container_name: sub-store
    restart: unless-stopped
    ports:
      - "9001:3001"
      - "9002:3000"
    volumes:
      - ${SUB_STORE_DATA_DIR}:/opt/app/data
    environment:
      - TZ=Asia/Shanghai
      - SUB_STORE_DATA_BASE_PATH=/opt/app/data
      - SUB_STORE_FRONTEND_BACKEND_PATH=/

  metacubexd:
    image: ${METACUBEXD_IMAGE}
    container_name: metacubexd
    restart: unless-stopped
    ports:
      - "9091:80"
    environment:
      - TZ=Asia/Shanghai
